### ISSUE TITLE
Redo some dialogue

### ISSUE THREAD

**Issue by stuffsmovie1** [colonelsalt/Rocket-Edition#1]
Hi, I don't know anything about coding, but I've been enjoying the game a lot and it's been a lot of fun playing through this take on pokemon.

One thing that really ruined it for me was the homophobic language that pops up every now and then. Can you remove it? I'd love to share this game with some friends, but I can't share a game with clear homophobic language. For instance, the work "gay" is used to refer to Clefairy. Really? Why?

**Comment by colonelsalt** [comment]
This is an artistic choice of in-game dialogue, spoken by a fictional gangster. It's self-evidently not an endorsement of any form of bigotry in the real world.

Speaking more generally, the game makes no attempts at being politically correct. Those who take issue with this have many other games they can consider playing instead.
